use std::env;
use std::fs;
use std::path::Path;

fn main() {
    let out_dir = env::var("OUT_DIR").unwrap();

    // Generate language list from data/languages/
    let lang_dir = Path::new("data/languages");
    let mut langs: Vec<String> = Vec::new();

    if let Ok(entries) = fs::read_dir(lang_dir) {
        for entry in entries.flatten() {
            let name = entry.file_name().to_string_lossy().to_string();
            if name.ends_with(".txt") && !name.starts_with('_') {
                let lang_name = name.trim_end_matches(".txt").to_string();
                langs.push(lang_name);
            }
        }
    }
    langs.sort();

    // Generate Rust source for the language data
    let mut code = String::new();
    code.push_str("// Auto-generated by build.rs — do not edit\n\n");

    // Embed each language file
    for lang in &langs {
        let const_name = lang.to_uppercase().replace('-', "_").replace(' ', "_");
        code.push_str(&format!(
            "const LANG_{}: &str = include_str!(concat!(env!(\"CARGO_MANIFEST_DIR\"), \"/data/languages/{}.txt\"));\n",
            const_name, lang
        ));
    }

    // Generate the map builder
    code.push_str("\npub fn build_language_map() -> HashMap<&'static str, &'static str> {\n");
    code.push_str(&format!("    let mut m = HashMap::with_capacity({});\n", langs.len()));
    for lang in &langs {
        let const_name = lang.to_uppercase().replace('-', "_").replace(' ', "_");
        code.push_str(&format!("    m.insert(\"{}\", LANG_{});\n", lang, const_name));
    }
    code.push_str("    m\n");
    code.push_str("}\n\n");

    // Generate the sorted name list
    code.push_str("pub const LANGUAGE_NAMES: &[&str] = &[\n");
    for lang in &langs {
        code.push_str(&format!("    \"{}\",\n", lang));
    }
    code.push_str("];\n");

    // Code languages list
    let code_dir = Path::new("data/code");
    let mut code_langs: Vec<String> = Vec::new();
    if let Ok(entries) = fs::read_dir(code_dir) {
        for entry in entries.flatten() {
            let name = entry.file_name().to_string_lossy().to_string();
            if name.ends_with(".txt") {
                code_langs.push(name.trim_end_matches(".txt").to_string());
            }
        }
    }
    code_langs.sort();

    for cl in &code_langs {
        let const_name = cl.to_uppercase().replace('-', "_").replace('+', "PLUS");
        code.push_str(&format!(
            "const CODE_{}: &str = include_str!(concat!(env!(\"CARGO_MANIFEST_DIR\"), \"/data/code/{}.txt\"));\n",
            const_name, cl
        ));
    }

    code.push_str("\npub fn build_code_map() -> HashMap<&'static str, &'static str> {\n");
    code.push_str(&format!("    let mut m = HashMap::with_capacity({});\n", code_langs.len()));
    for cl in &code_langs {
        let const_name = cl.to_uppercase().replace('-', "_").replace('+', "PLUS");
        code.push_str(&format!("    m.insert(\"code {}\", CODE_{});\n", cl, const_name));
    }
    code.push_str("    m\n");
    code.push_str("}\n\n");

    code.push_str("pub const CODE_LANGUAGE_NAMES: &[&str] = &[\n");
    for cl in &code_langs {
        code.push_str(&format!("    \"code {}\",\n", cl));
    }
    code.push_str("];\n");

    let dest = Path::new(&out_dir).join("languages_generated.rs");
    fs::write(dest, code).unwrap();

    println!("cargo:rerun-if-changed=data/languages");
    println!("cargo:rerun-if-changed=data/code");
}
